[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "Wave Dispersion"
version = "0.1.0"
description = "Numerical library for calculating and plotting dispersion curves of various materials."
authors = ["Rafal Wrobel <rwrobel@student.agh.edu.pl>"]

[tool.poetry.dependencies]
python = "^3.8"
scipy = "^1.11.4"
matplotlib = "^3.8.2"